### ISSUE TITLE
Looking forward for the next versions

### ISSUE THREAD

**Issue by nunobrum** [rliangcn/newSpice#1]
Hi @rliangcn,

Congratulations for the "creation" of newSpice.
My name is Nuno and I am the creator of spicelib. 
I have nothing against you using spicelib to adapt to your own needs and preferences.
This is why the library is public and I've chosen the licence that allows it. 
**It is of course required that you reference the sources, credit the original authors and make your own work public.**

I can already tell you that developping and maintaining this library takes a lot of effort and it gives you nothing in return other than thanks and likes.
This is why I've been eager to find collaborators to help answer requests for help, document and imlement new features.

I guess you had already considered the option of cooperating, but decided to fork your own version of it, so, I'm not going to propose it to you.

Wishing you good luck on the development of newSpice. I am quite curious to know what you will add to it.

Regards,
@nunobrum

**Comment by rliangcn** [comment]
Hello @nunobrum ,

I appreciate your approval of starting the newSpice version. I will obey your requirements.

The basic idea of newSpice is listed in 'readme.md'. Generally, I want to make it as simple as possible and provide users with an easy-to-use simulation workflow. However, these simplifications and modifications will likely affect the existing features in spicelib, so I decided to start newSpice to implement them here.

I will still work on spicelib and, at the same time, develop newSpice. The newSpice is based on spicelib, so the same changes may suit both. You can cherry-pick what is good for spicelib and needn't feel bad if you refuse them. 

For the next step, I'm going to update the editor. It may take time, but you will receive a pull request.

Thanks for the spicelib, where I learned many things, and for your suggestions!

Regards,
Robert Liang @rliangcn
